services:
  - type: web
    name: gestor-tareas-api
    runtime: docker
    repo: https://github.com/Joel-S-Florian/gestor-tareas-api
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DB_PROVIDER
        value: POSTGRES
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: JWT__Secret
        sync: false
      - key: JWT__Issuer
        value: gestor-tareas-api
      - key: JWT__Audience
        value: gestor-tareas-spa
      - key: CORS__AllowedOrigins
        sync: false