services:
  - type: web
    name: gestor-tareas-api
    runtime: dotnet
    repo: https://github.com/Joel-S-Florian/gestor-tareas-api
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: JWT__Secret
        sync: false
      - key: JWT__Issuer
        value: gestor-tareas-api
      - key: JWT__Audience
        value: gestor-tareas-spa
      - key: CORS__AllowedOrigins
        sync: false
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: dotnet out/gestor-tareas-api.dll
